---
Install: 
    date: Thu, 22 Jul 10 18:16:23 -0400
App: 
    base: 
    baseUrl: 
    timezone: America/Santiago
    name: Regala Una Plaza
Site:
    name: 
    theme: finalus
    admin_theme: finalus
    status: 1
Hook: 
    bootstraps: core,acl
    components: 
    routes: core,acl
