---
Install: 
    date: Thu, 22 Jul 10 18:16:23 -0400
App: 
    base: 
    baseUrl: 
    timezone: America/Santiago
    theme: cleanity
    name: Regala Una Plaza 
    url: http://plaza_cake/ 
    email: jmashburn@iwobble.com
    votes:
        limits:
            active: true
            limit: 3 //
            expiry: 1 //The number of days 
            all: true
            force_login: false    
    donations:
        cost: 25,000    
    allowedIps:
        200.30.250.18
        69.169.164.173
        
        
Site:
    name: 
    theme: 
    admin_theme: broom
    status: 1
Hook: 
    bootstraps: acl,searchable
    components: 
    routes: acl,searchable  
    
Email:
    IsSMTP: true,
    IsHTML: true,
    SMTPAuth: true,
    SMTPSecure: ssl,
    Host: smtp.gmail.com
    Port: 465,
    Username: jmashburn,
    Password: j1a2r3e4d5,
    Wordwrap: 50,
    From: info@iwobble.com
    FromName: iWobble Info
    ReplyTo: info@iwobble.com
